source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Bugtags'
pod "LiquidFloatingActionButton"
pod 'FMDB'
pod 'pop', '~> 1.0'
pod 'Alamofire', '~> 1.3'
pod 'Kingfisher', '~> 1.4'
pod 'SnapKit', '~> 0.12.0'
pod 'SwiftyJSON', '~> 2.2.1'
pod 'MJExtension'
